apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      version: blue
  template:
    metadata:
      labels:
        app: notification-service
        version: blue
    spec:
      containers:
      - name: notification-service
        image: 924055965473.dkr.ecr.ap-southeast-2.amazonaws.com/notification-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: REDSHIFT_HOST
          value: "moonagent-cluster.cpcjx7hrgnyr.ap-southeast-2.redshift.amazonaws.com"
        - name: REDSHIFT_DB
          value: "moonmetrics_db"
        - name: REDSHIFT_USER
          value: "admin"
        - name: REDSHIFT_PASSWORD
          value: "DATAst2012"
