apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      version: green
  template:
    metadata:
      labels:
        app: notification-service
        version: green
    spec:
      containers:
      - name: notification-service
        image: 924055965473.dkr.ecr.ap-southeast-2.amazonaws.com/notification-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: RDS_HOST
          value: "moontracker-db.cfsm0qyek393.ap-southeast-2.rds.amazonaws.com"
        - name: RDS_DB
          value: "moontracker"
        - name: RDS_USER
          value: "admin"
        - name: RDS_PASSWORD
          value: "Moon1234!"
