apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-service
      version: green
  template:
    metadata:
      labels:
        app: agent-service
        version: green
    spec:
      containers:
      - name: agent-service
        image: 924055965473.dkr.ecr.ap-southeast-2.amazonaws.com/agent-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: REDSHIFT_HOST
          value: "moonagent-cluster.cpcjx7hrgnyr.ap-southeast-2.redshift.amazonaws.com"
        - name: REDSHIFT_DB
          value: "moonmetrics"
        - name: REDSHIFT_USER
          value: "admin"
        - name: REDSHIFT_PASSWORD
          value: "Moon1234!"
