apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-service
      version: green
  template:
    metadata:
      labels:
        app: agent-service
        version: green
    spec:
      containers:
      - name: agent-service
        image: 924055965473.dkr.ecr.ap-southeast-2.amazonaws.com/agent-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: RDS_HOST
          value: "moontracker-rds.cfsm0qyek393.ap-southeast-2.rds.amazonaws.com"
        - name: RDS_DB
          value: "moontracker"
        - name: RDS_USER
          value: "admin"
        - name: RDS_PASSWORD
          value: "Moon1234!"
