apiVersion: v1
kind: Service
metadata:
  name: agent-service
spec:
  type: LoadBalancer
  selector:
    app: agent-service
    version: blue  # this will be patched to "green" during deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
