apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregator-cron
spec:
  schedule: "0 */2 * * *"  # Every 2 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aggregator-job
            image: aggregator-service:latest
            imagePullPolicy: IfNotPresent
            command: ["python", "aggregate_job.py"]
          restartPolicy: OnFailure
