apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-service
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
      - name: aggregator-service
        image: 924055965473.dkr.ecr.ap-southeast-2.amazonaws.com/aggregator-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
