apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-service
      version: blue
  template:
    metadata:
      labels:
        app: aggregator-service
        version: blue
    spec:
      containers:
      - name: aggregator-service
        image: 924055965473.dkr.ecr.ap-southeast-2.amazonaws.com/aggregator-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
        env:
        - name: REDSHIFT_HOST
          value: "moonagent-cluster.cpcjx7hrgnyr.ap-southeast-2.redshift.amazonaws.com"
        - name: REDSHIFT_DB
          value: "moonmetrics_db"
        - name: REDSHIFT_USER
          value: "admin"
        - name: REDSHIFT_PASSWORD
          value: "DATAst2012"
        - name: NOTIFICATION_URL
          value: "a3f3a89b5ff9b4b58976edeee28b450b-375560315.ap-southeast-2.elb.amazonaws.com/notify"
