apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      containers:
      - name: integration-service
        image: 924055965473.dkr.ecr.ap-southeast-2.amazonaws.com/integration-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
