apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
      version: green
  template:
    metadata:
      labels:
        app: integration-service
        version: green
    spec:
      containers:
      - name: integration-service
        image: 924055965473.dkr.ecr.ap-southeast-2.amazonaws.com/integration-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: REDSHIFT_HOST
          value: "moonagent-cluster.cpcjx7hrgnyr.ap-southeast-2.redshift.amazonaws.com"
        - name: REDSHIFT_DB
          value: "moonmetrics_db"
        - name: REDSHIFT_USER
          value: "admin"
        - name: REDSHIFT_PASSWORD
          value: "DATAst2012"
