apiVersion: v1
kind: Service
metadata:
  name: integration-service
spec:
  type: LoadBalancer
  selector:
    app: integration-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
